openapi: 3.0.1
info:
  title: 'Manager API for a Service Poller'
  contact:
    name: 'Nazmul Islam'
    url: 'https://www.linkedin.com/in/nazmul-islam-7aaa5173/'
  license:
    name: 'MIT License'
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
paths:
  /api/v1/services:
    summary: 'Path used to manage services belongs to a user.'
    description: "The REST endpoint/path used to get, create, and delete single instances\nof `Service` for a user.  This path contains `GET`, `POST`, and `DELETE` operations\nused to perform the get, create, and delete tasks, respectively."
    get:
      summary: 'Get Service list with User JWT Token.'
      description: 'Gets the list of a `Service` with User JWT Token.'
      operationId: getServiceList
      tags:
        - services
      parameters:
        - name: pollerId
          in: query
          description: 'Provide poller ID for filter'
          required: false
          schema:
            type: integer
            format: int32
        - name: pollerName
          in: query
          description: 'Provide poller name for filter'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Successful response - returns a single `Service`.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Services'
        '204':
          description: 'No poller found.'
        '401':
          description: 'Expired Token '
        default:
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - loggedUserToken: []
      x-vertx-event-bus: poller.service_manager
    post:
      summary: 'Create a Service with with User JWT Token.'
      description: 'Creates a new instance of a `Service` with User JWT Token.'
      operationId: createService
      tags:
        - services
      requestBody:
        description: 'A new `Service` to be created.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServicePostDTO'
        required: true
      responses:
        '201':
          description: 'Successful created the poller.'
        '400':
          description: "Invalid URL io poller"
        '401':
          description: 'Expired Token '
        default:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - loggedUserToken: []
      x-vertx-event-bus: poller.service_manager
    delete:
      summary: 'Delete services'
      description: 'Deletes all existing `Service` for the user.'
      operationId: deleteAllService
      tags:
        - services
      responses:
        '204':
          description: 'Successfully deleted all poller  with User JWT Token.'
        '401':
          description: 'Operation is not permitted.'
        default:
          description: 'Internal server error.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - loggedUserToken: []
      x-vertx-event-bus: poller.service_manager
  /api/v1/services/{serviceId}:
    summary: 'Path used to manage services belongs to a user.'
    description: "The REST endpoint/path used to update single instances\nof `Service` for a user.  This path contains `PUT` operations\nused to perform the update tasks, respectively."
    put:
      summary: 'Update a Service'
      description: 'Updates an existing `Service` with User JWT Token.'
      operationId: updateService
      tags:
        - services
      requestBody:
        description: 'Updated a `Service` information with User JWT Token.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServicePutDTO'
        required: true
      responses:
        '202':
          description: 'Successfully update a service.'
        '401':
          description: 'Expired Token '
        '500':
          description: 'Could not perform operation. Internal server error.'
        default:
          description: 'Internal server error.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - loggedUserToken: []
      x-vertx-event-bus: poller.service_manager
    parameters:
      - name: serviceId
        in: path
        description: 'A unique identifier for service.'
        required: true
        schema:
          type: string
  /api/v1/login:
    post:
      summary: Login
      operationId: login
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              type: object
              properties:
                username:
                  type: string
                password:
                  $ref: '#/components/schemas/Password'
        required: true
      responses:
        '200':
          description: 'Returns the JWT token'
          content:
            text/plain: {}
        '400':
          description: 'Wrong username or password'
          content:
            text/plain: {}
      x-vertx-event-bus: user.service_manager
  /api/v1/register:
    post:
      summary: Register
      operationId: register
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              type: object
              properties:
                username:
                  type: string
                password:
                  $ref: '#/components/schemas/Password'
        required: true
      responses:
        '200':
          description: 'Returns the JWT Token'
          content:
            text/plain:
              x-description: 'Login token'
        '400':
          description: 'Username already exists'
          content:
            text/plain: {}
      x-vertx-event-bus: user.service_manager
components:
  schemas:
    Service:
      type: object
      required:
        - id
        - name
        - url
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        url:
          type: string
        status:
          type: string
    Services:
      type: array
      items:
        $ref: "#/components/schemas/Service"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ServicePostDTO:
      type: object
      required:
        - name
        - url
      properties:
        name:
          type: string
        url:
          type: string
    ServicePutDTO:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    Password:
      minLength: 6
      type: string
  securitySchemes:
    loggedUserToken:
      type: http
      scheme: bearer
  x-vertx-service-gen:
    poller.service_manager: PollerService
    user.service_manager: UserService
