DROP TABLE IF EXISTS SERVICE;
CREATE TABLE IF NOT EXISTS SERVICE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    url VARCHAR(250) NOT NULL,
    userId VARCHAR(250) NOT NULL,
    createdDate VARCHAR(100) NOT NULL,
    status VARCHAR(250) DEFAULT 'UNKNOWN'
);
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(250) NOT NULL
);
ALTER TABLE SERVICE
    ADD FOREIGN KEY (userId)
    REFERENCES USERS (username);
ALTER TABLE SERVICE ADD CONSTRAINT SERVICE_NAME_USER_CONST UNIQUE (name, userId);